batch_size: 8
data_path_train: ./data/train0.8,1.0_sr16000_len10.npy
data_path_valid: ./data/valid0.8,1.0_sr16000_len769.npy
epochs: 150
learning_rate: 0.001
max_to_keep: 100
n_frequencies: null
sampling_rate: 16000
sr: 16000
