sampling_rate: &sr_ 16000
n_frequencies: &nfreq
learning_rate: 0.001
epochs: 100 #75 #50
data_path_train: "./data/train0.8,1.0_sr16000_len10.npy"
data_path_valid: "./data/valid0.8,1.0_sr16000_len769.npy"
sr: 16000
max_to_keep: 100
batch_size: 8